Repository kubernetes-sigs/provider-aws-test-infra, pull requests merged in 2023-04, with the labels that each got.

#1 Update OWNERS - Add `dims`
  OWNERS
Labels: approved, lgtm, size/XS, cncf-cla: yes

#5 Ubuntu 2204 Instance config
  config/aws-instance.yaml
  config/configure.sh
  config/ubuntu2204.yaml
Labels: size/L, approved, lgtm, cncf-cla: yes

#6 switch default user id for ubuntu image
  config/ubuntu2204.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#9 Force the old style cgroup non systemd
  config/configure.sh
Labels: approved, size/XS, cncf-cla: yes

#8 Add ec2-user to root group to allow access to containerd.sock
  config/ubuntu2204.yaml
Labels: approved, size/XS, cncf-cla: yes
