Repository kubernetes-sigs/provider-aws-test-infra, pull requests merged in 2023-08, with the labels that each got.

#92 remove the runtime.slice configuration
  config/userdata-al2023.sh
Labels: approved, lgtm, size/XS, cncf-cla: yes

#93 ensure userdata works when image-config file isn't being used
  test/e2e_node/remote/aws/aws_runner.go
Labels: approved, lgtm, size/M, cncf-cla: yes

#98 Drop the dirty suffix in version number
  kubetest2-ec2/pkg/deployer/utils/source.go
Labels: approved, size/XS, cncf-cla: yes

#99 implement DumpClusterLogs - Download kubelet/cloud-init/cluster-info logs
  kubetest2-ec2/pkg/deployer/deployer.go
  kubetest2-ec2/pkg/deployer/dump.go
Labels: approved, size/M, cncf-cla: yes

#101 Support new parameter "num-nodes" for worker nodes
  kubetest2-ec2/config/ubuntu2204.yaml
  kubetest2-ec2/pkg/deployer/deployer.go
  kubetest2-ec2/pkg/deployer/up.go
  kubetest2-ec2/pkg/deployer/utils/random.go
Labels: size/L, approved, cncf-cla: yes

#103 capture containerd related logs
  kubetest2-ec2/pkg/deployer/dump.go
Labels: approved, size/S, cncf-cla: yes

#106 Install ecr credential provider
  kubetest2-ec2/config/ubuntu2204.yaml
Labels: approved, size/S, cncf-cla: yes

#109 use the usual directory for CNI as AWS VPC CNI does not like alternate directories
  config/configure.sh
Labels: approved, size/XS, cncf-cla: yes

#111 Maintain scripts outside yaml file
  kubetest2-ec2/config/configure.sh
  kubetest2-ec2/config/ubuntu2204.yaml
  kubetest2-ec2/pkg/deployer/up.go
Labels: size/L, approved, cncf-cla: yes

#113 Switch to cilium from AWS VPC CNI
  kubetest2-ec2/config/ubuntu2204.yaml
Labels: approved, cncf-cla: yes

#114 use singular --image on the command line, also make it optional to specify
  kubetest2-ec2/pkg/deployer/deployer.go
  kubetest2-ec2/pkg/deployer/up.go
  kubetest2-ec2/pkg/deployer/utils/ssm.go
Labels: size/L, approved, cncf-cla: yes

#115 Do not bail out after creating logs directory
  kubetest2-ec2/pkg/deployer/dump.go
Labels: approved, size/XS, cncf-cla: yes

#116 Better directory to pick up binaries from
  kubetest2-ec2/pkg/deployer/build/build.go
Labels: approved, size/XS, cncf-cla: yes

#117 Embed the configure.sh and ubuntu2204.yaml into the binary
  kubetest2-ec2/config/embed.go
  kubetest2-ec2/pkg/deployer/up.go
Labels: approved, size/M, cncf-cla: yes

#118 Ability to specify a version that already exists in the s3 bucket
  kubetest2-ec2/pkg/deployer/build/options.go
  kubetest2-ec2/pkg/deployer/up.go
Labels: cncf-cla: yes

#119 Switch back to aws vpc cni - Revert systemd-udev change (MACAddressPolicy) that disables networking from pods
  kubetest2-ec2/config/ubuntu2204.yaml
Labels: approved, size/S, cncf-cla: yes

#120 Dump logs when Deployer Up() fails for some reason
  kubetest2-ec2/pkg/deployer/up.go
Labels: approved, size/XS, cncf-cla: yes

#121 Lookup version when one is NOT specified
  kubetest2-ec2/pkg/deployer/up.go
Labels: approved, size/XS, cncf-cla: yes

#122 Avoid adding instance to array multiple times
  kubetest2-ec2/pkg/deployer/up.go
Labels: approved, cncf-cla: yes

#123 Better defaults for arm64
  kubetest2-ec2/pkg/deployer/up.go
Labels: cncf-cla: yes

#124 Grab vpc vni related logs
  kubetest2-ec2/pkg/deployer/dump.go
  kubetest2-ec2/pkg/deployer/remote/ssh.go
Labels: approved, size/M, cncf-cla: yes

#126 Tweak network settings to avoid problems during huge pod churn
  kubetest2-ec2/config/ubuntu2204.yaml
Labels: cncf-cla: yes

#127 Dump vpc cni logs first
  kubetest2-ec2/pkg/deployer/dump.go
Labels: approved, cncf-cla: yes

#128 Instance types are way too small
  kubetest2-ec2/pkg/deployer/deployer.go
  kubetest2-ec2/pkg/deployer/up.go
Labels: approved, size/XS, cncf-cla: yes

#129 Add a README.md for kubetest2-ec2
  kubetest2-ec2/README.md
Labels: size/L, approved, cncf-cla: yes

#133 Allow standing up clusters from release artifacts
  kubetest2-ec2/README.md
  kubetest2-ec2/config/ubuntu2204.yaml
  kubetest2-ec2/pkg/deployer/build.go
  kubetest2-ec2/pkg/deployer/build/options.go
  kubetest2-ec2/pkg/deployer/runner.go
  kubetest2-ec2/vendor/golang.org/x/exp/LICENSE
  kubetest2-ec2/vendor/golang.org/x/exp/PATENTS
  kubetest2-ec2/vendor/golang.org/x/exp/maps/maps.go
Labels: cncf-cla: yes

#140 fix staging bucket variations
  kubetest2-ec2/config/ubuntu2204.yaml
Labels: approved, size/XS, cncf-cla: yes

#141 Drop external cloud provider for now
  kubetest2-ec2/config/kubeadm-init.yaml
  kubetest2-ec2/config/kubeadm-join.yaml
Labels: approved, size/XS, cncf-cla: yes

#142 use metadata api to get public ip
  kubetest2-ec2/config/ubuntu2204.yaml
Labels: approved, size/XS, cncf-cla: yes

#145 Extract shell script from cloud init yaml
  kubetest2-ec2/config/kubeadm-join.yaml
  kubetest2-ec2/config/run-kubeadm.sh
  kubetest2-ec2/config/ubuntu2204.yaml
  kubetest2-ec2/pkg/deployer/runner.go
  kubetest2-ec2/pkg/deployer/utils/ec2.go
  kubetest2-ec2/pkg/deployer/utils/userdata.go
Labels: size/L, approved, cncf-cla: yes

#146 CLI param to enable external AWS cloud provider
  kubetest2-ec2/config/kubeadm-init.yaml
  kubetest2-ec2/config/kubeadm-join.yaml
  kubetest2-ec2/config/ubuntu2204.yaml
  kubetest2-ec2/pkg/deployer/deployer.go
  kubetest2-ec2/pkg/deployer/runner.go
  kubetest2-ec2/pkg/deployer/utils/userdata.go
Labels: approved, size/M, cncf-cla: yes

#147 Update README with `--external-cloud-provider` flag
  kubetest2-ec2/README.md
Labels: approved, lgtm, size/S, cncf-cla: yes

#148 Build test binaries in local platform only if different from target platform
  kubetest2-ec2/pkg/deployer/build/build.go
  kubetest2-ec2/pkg/deployer/build/make.go
Labels: approved, lgtm, size/S, cncf-cla: yes

#150 Allow CI jobs to describe/list/pull from s3 bucket
  kubetest2-ec2/config/run-kubeadm.sh
  kubetest2-ec2/pkg/deployer/utils/role.go
Labels: approved, size/XS, cncf-cla: yes
