Repository kubernetes-sigs/provider-aws-test-infra, pull requests merged in 2023-12, with the labels that each got.

#232 Add rpcbind back, for nfs
  kubetest2-ec2/config/ubuntu2204.yaml
Labels: size/XS, cncf-cla: yes

#233 ensure we pick up only one line
  hack/build-ami.sh
  hack/make-rules/test-e2e-node.sh
Labels: cncf-cla: yes

#234 turn snippet used in CI job definition into a script
  kubetest2-ec2/scripts/check-ami.sh
Labels: approved, size/M, cncf-cla: yes

#235 fail fast when creds are not present
  kubetest2-ec2/scripts/check-ami.sh
Labels: cncf-cla: yes

#231 Enable full AWS SDK credential chain
  kubetest2-ec2/pkg/deployer/runner.go
Labels: approved, lgtm, size/S, cncf-cla: yes

#237 add another variable NODE_OS_ARCH
  kubetest2-ec2/scripts/check-ami.sh
Labels: approved, size/XS, cncf-cla: yes

#241 copy both directories
  hack/populate-s3.sh
Labels: approved, size/XS, cncf-cla: yes

#246 Try another alternative
  kubetest2-ec2/config/al2023.sh
Labels: cncf-cla: yes

#247 disable expansion within nested cat/EOF
  kubetest2-ec2/config/al2023.sh
Labels: cncf-cla: yes

#248 go back to what we had before for amazon-ec2-net-utils
  kubetest2-ec2/config/al2023.sh
Labels: approved, cncf-cla: yes

#249 do not remove amazon-ec2-net-utils
  kubetest2-ec2/config/al2023.sh
Labels: cncf-cla: yes

#250 hack amazon-ec2-net-utils - take 1
  kubetest2-ec2/config/al2023.sh
Labels: approved, cncf-cla: yes

#251 Revert hack amazon ec2 net utils take 1
  kubetest2-ec2/config/al2023.sh
Labels: size/XS, cncf-cla: yes

#252 Remove custom amazon-vpc-cni configuration
  kubetest2-ec2/config/ubuntu2204.yaml
Labels: approved, size/XS, cncf-cla: yes

#256 switch arm64 instance type to more closely match the amd64 one
  kubetest2-ec2/pkg/deployer/deployer.go
Labels: approved, size/XS, cncf-cla: yes

#257 do not fetch sha256 either
  hack/build-ami.sh
Labels: approved, size/XS, cncf-cla: yes

#258 remove another line from install-worker.sh
  hack/build-ami.sh
Labels: cncf-cla: yes

#259 testing proposed updates to amazon-eks-ami - PR 1539
  kubetest2-ec2/config/al2023.sh
Labels: approved, size/S, cncf-cla: yes

#262 Use a single script for both AL2 and AL2023 AMI(s)
  kubetest2-ec2/config/al2.sh
  kubetest2-ec2/config/al2023.sh
Labels: approved, size/M, cncf-cla: yes

#263 Add a conditional for removing duplicates in resolv.conf
  kubetest2-ec2/config/al2023.sh
Labels: cncf-cla: yes

#266 pick the right package manager for al2/al2023
  kubetest2-ec2/config/al2023.sh
Labels: cncf-cla: yes

#267 add iptables reset back
  kubetest2-ec2/config/al2023.sh
Labels: approved, size/XS, cncf-cla: yes

#268 adding one more thing back
  kubetest2-ec2/config/al2023.sh
Labels: approved, cncf-cla: yes

#270 Add support for aws external load balancer
  kubetest2-ec2/config/ubuntu2204.yaml
  kubetest2-ec2/pkg/deployer/deployer.go
  kubetest2-ec2/pkg/deployer/runner.go
Labels: approved, size/S, cncf-cla: yes

#271 externalize/gzip run-post-install.sh
  kubetest2-ec2/config/embed.go
  kubetest2-ec2/config/run-post-install.sh
  kubetest2-ec2/config/ubuntu2204.yaml
  kubetest2-ec2/pkg/deployer/runner.go
  kubetest2-ec2/pkg/deployer/utils/userdata.go
Labels: size/L, approved, cncf-cla: yes

#272 fix typo in shell script variable name
  kubetest2-ec2/pkg/deployer/runner.go
Labels: approved, cncf-cla: yes

#273 Better kubectl wait .. wait on deployments
  kubetest2-ec2/config/run-post-install.sh
Labels: approved, cncf-cla: yes

#274 Throw in AWS EBS CSI driver
  kubetest2-ec2/config/run-post-install.sh
Labels: approved, cncf-cla: yes

#275 Switch on IMDSv2 for all instances by default
  kubetest2-ec2/config/run-kubeadm.sh
  kubetest2-ec2/config/ubuntu2204.yaml
  kubetest2-ec2/pkg/deployer/utils/ec2.go
Labels: approved, size/S, cncf-cla: yes

#276 Update to newest versions of dependencies in GH action
  .github/workflows/update-deps.yml
Labels: cncf-cla: yes
