Repository kubernetes-sigs/provider-aws-test-infra, pull requests merged in 2023-07, with the labels that each got.

#61 Scripts to build amazon-eks-ami based AMI from scratch for testing
  .gitignore
  hack/build-ami.sh
  hack/populate-s3.sh
Labels: size/L, approved, cncf-cla: yes

#63 option to BUILD_EKS_AMI
  hack/build-ami.sh
  hack/make-rules/test-e2e-node.sh
Labels: approved, cncf-cla: yes

#66 use sudo to install 10-testcni.conflist
  config/userdata.sh
Labels: approved, size/XS, cncf-cla: yes

#67 Build EKS AMI and then run node e2e tests using that new AMI
  hack/build-ami.sh
  hack/bump-k8s.sh
  hack/make-rules/test-e2e-node.sh
  hack/populate-s3.sh
Labels: approved, size/M, cncf-cla: yes

#68 fix check for existing image
  hack/make-rules/test-e2e-node.sh
Labels: approved, cncf-cla: yes

#69 fix setting TEST_INFRA_ROOT
  hack/make-rules/test-e2e-node.sh
Labels: approved, cncf-cla: yes

#73 Add ec2-instance-connect package for al2023
  config/al2023-6.1.yaml
Labels: approved, size/XS, cncf-cla: yes

#75 Support for testing al2023 based eks images
  hack/build-ami.sh
  hack/make-rules/test-e2e-node.sh
Labels: approved, size/S, cncf-cla: yes

#76 add support to build arm64 based EKS AMI(s)
  hack/build-ami.sh
  hack/make-rules/test-e2e-node.sh
Labels: approved, size/S, cncf-cla: yes

#77 fix eks instance type for arm64
  hack/make-rules/test-e2e-node.sh
Labels: approved, size/XS, cncf-cla: yes

#78 fixup references to x86_64 irrespective of BUILD_EKS_AMI_OS setting
  hack/build-ami.sh
Labels: approved, cncf-cla: yes

#79 separate the instance type determination from the _OS check
  hack/make-rules/test-e2e-node.sh
Labels: approved, size/XS, cncf-cla: yes

#81 Ensure we use systemd cgroup with al2023
  config/userdata-al2023.sh
  hack/make-rules/test-e2e-node.sh
Labels: approved, size/M, cncf-cla: yes

#82 Default arch is amd64 when building eks image
  hack/build-ami.sh
Labels: approved, size/XS, cncf-cla: yes

#84 set packer variables when BUILD_EKS_AMI_OS is NOT arm64
  hack/build-ami.sh
Labels: approved, size/XS, cncf-cla: yes

#85 fix typo in file name
  hack/build-ami.sh
Labels: approved, cncf-cla: yes

#86 remove the systemd hack on al2023
  config/userdata-al2023.sh
Labels: approved, lgtm, size/S, cncf-cla: yes

#87 Trying to fix update dependencies action
  hack/bump-k8s.sh
Labels: approved, size/XS, cncf-cla: yes

#88 Add a new dependency from staging - k8s.io/apiextensions-apiserver
  go.mod
Labels: approved, size/XS, cncf-cla: yes

#80 Run e2e tests without specifying an image config file
  hack/make-rules/test-e2e-node.sh
Labels: approved, lgtm, size/S, cncf-cla: yes

#90 Drop sha256 sum check for CI
  hack/build-ami.sh
Labels: approved, cncf-cla: yes
