Repository kubernetes-sigs/provider-aws-test-infra, pull requests merged in 2023-06, with the labels that each got.

#10 Fix k/k path
  hack/make-rules/test-e2e-node.sh
Labels: approved, lgtm, size/XS, cncf-cla: yes

#11 Allow access to SSH
  hack/make-rules/test-e2e-node.sh
Labels: approved, lgtm, size/XS, cncf-cla: yes

#13 Revert "Fix k/k path"
  hack/make-rules/test-e2e-node.sh
Labels: approved, lgtm, size/XS, cncf-cla: yes

#14 Add a new image for e2e-node testing with AL2023 (kernel 6.1)
  config/al2023-6.1.yaml
  config/aws-instance.yaml
Labels: approved, size/M, cncf-cla: yes

#15 Enable systemd cgroup driver
  config/configure.sh
  test/e2e_node/jenkins/default-kubelet-config.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#16 Drop Temporary SG hack for aws ec2 authorize-security-group-ingress
  hack/make-rules/test-e2e-node.sh
Labels: approved, lgtm, size/XS, cncf-cla: yes

#19 Adding configuration for arm64 based CI jobs
  config/aws-instance-arm64.yaml
  config/configure.sh
Labels: approved, lgtm, size/M

#18 Prep for arm64 based ci jobs
  hack/make-rules/test-e2e-node.sh
Labels: approved, lgtm, size/XS

#21 set USE_DOCKERIZED_BUILD to false explicitly
  hack/make-rules/test-e2e-node.sh
Labels: approved, size/XS, cncf-cla: yes

#22 Pick suitable instance type for arm64
  config/aws-instance-arm64.yaml
Labels: approved, cncf-cla: yes

#23 create the CNI directory and template
  config/configure.sh
Labels: approved, size/S, cncf-cla: yes

#24 Drop dependency on "jq"
  config/configure.sh
Labels: approved, size/XS, cncf-cla: yes

#25 Add better defaults for arm64/e2e-node ci jobs
  hack/make-rules/test-e2e-node.sh
Labels: approved, size/XS, cncf-cla: yes

#26 cleanup cni.template
  config/configure.sh
Labels: approved, size/XS, cncf-cla: yes

#27 forgot to delete one line
  config/configure.sh
Labels: approved, cncf-cla: yes

#28 Updates to ebs disk size and dealing with instances
  hack/make-rules/test-e2e-node.sh
  run.sh
  test/e2e_node/remote/aws/aws_runner.go
Labels: approved, cncf-cla: yes

#29 Tweak inotify settings
  config/configure.sh
Labels: approved, cncf-cla: yes

#30 Use specific version of containerd for arm64 - v1.6.21
  config/configure.sh
Labels: approved, size/XS, cncf-cla: yes

#31 if there are serial tests use one ginkgo node
  hack/make-rules/test-e2e-node.sh
Labels: approved, size/S, cncf-cla: yes

#32 whoops we lost "focus" param
  hack/make-rules/test-e2e-node.sh
Labels: approved, cncf-cla: yes

#34 Bump instance type size and switch back to newest containerd
  config/aws-instance-arm64.yaml
  config/configure.sh
Labels: approved, cncf-cla: yes

#35 Bump disk still running out of space
  test/e2e_node/remote/aws/aws_runner.go
Labels: approved, size/XS, cncf-cla: yes

#36 Lookup root device name for AMI
  test/e2e_node/remote/aws/aws_runner.go
Labels: approved, size/XS, cncf-cla: yes

#37 Default to 4 hours of test timeout
  hack/make-rules/test-e2e-node.sh
Labels: approved, size/XS, cncf-cla: yes

#38 whoops! set the actual timeout
  hack/make-rules/test-e2e-node.sh
Labels: approved, size/XS, cncf-cla: yes

#40 Drop back to lower size of instance type
  config/aws-instance-arm64.yaml
Labels: approved, size/XS

#41 Ensure instance-id resolves to the host ip address on ubuntu
  config/ubuntu2204.yaml
Labels: approved, size/XS, cncf-cla: yes

#42 Graceful node shutdown conflicts with unattended-upgrades package
  config/ubuntu2204.yaml
Labels: approved, cncf-cla: yes

#39 Add kubetest2 support
  Makefile
  hack/make-rules/test-e2e-node.sh
  test/e2e_node/remote/aws/aws_runner.go
Labels: size/L, cncf-cla: yes

#43 Move EKS images to another yaml file
  config/aws-instance-eks.yaml
  config/aws-instance.yaml
Labels: approved, size/S, cncf-cla: yes

#44 install nfs-common package as a e2e node test is mounting an nfs server
  config/ubuntu2204.yaml
Labels: approved, cncf-cla: yes

#45 Capture exit code from piped process
  hack/make-rules/test-e2e-node.sh
Labels: approved, size/S, cncf-cla: yes

#47 Install ecr-credential-provider during node e2e tests
  vendor/k8s.io/kubernetes/test/e2e_node/remote/utils.go
Labels: approved, size/S, cncf-cla: yes

#50 forgot to checkout kubernetes
  .github/workflows/update-deps.yml
Labels: cncf-cla: yes

#52 hmm we will need path to ensure it goes to k8s.io/kubernetes
  .github/workflows/update-deps.yml
Labels: approved, cncf-cla: yes

#53 use relative root instead of GOPATH
  hack/bump-k8s.sh
Labels: cncf-cla: yes

#54 better detection of kubernetes directory (take 3)
  hack/bump-k8s.sh
Labels: cncf-cla: yes

#55 try checking out both github repos correctly again (take 4)
  .github/workflows/update-deps.yml
Labels: cncf-cla: yes

#57 change working-directory to path
  .github/workflows/update-deps.yml
Labels: approved, cncf-cla: yes

#58 path should be indented right
  .github/workflows/update-deps.yml
Labels: cncf-cla: yes

#59 provider-aws-test-infra uses main not master
  .github/workflows/update-deps.yml
Labels: cncf-cla: yes
