Repository kubernetes-sigs/provider-aws-test-infra, pull requests merged in 2024-07, with the labels that each got.

#310 Add feature gates for kube-controller-manager and kube-scheduler
  kubetest2-ec2/config/kubeadm-init.yaml
Labels: approved, size/XS, cncf-cla: yes

#312 Bump CSI driver, Cert Manager, Load Balancer and NVIDIA device plugin versions
  kubetest2-ec2/config/run-post-install.sh
Labels: approved, size/XS, cncf-cla: yes

#318 Set AWS_VPC_K8S_CNI_EXTERNALSNAT to true
  kubetest2-ec2/config/al2023.sh
  kubetest2-ec2/config/run-post-install.sh
  kubetest2-ec2/config/ubuntu2204.yaml
Labels: approved, size/M, cncf-cla: yes

#322 Use AWS_VPC_K8S_CNI_EXTERNALSNAT - drop AWS_VPC_K8S_CNI_EXCLUDE_SNAT_CIDRS
  config/configure.sh
  config/userdata-al2023.sh
  config/userdata.sh
  kubetest2-ec2/config/configure.sh
  kubetest2-ec2/config/run-post-install.sh
Labels: approved, size/M, cncf-cla: yes

#324 add testnet bridge back
  config/userdata-al2023.sh
  config/userdata.sh
Labels: approved, size/M, cncf-cla: yes

#326 Avoid coredns loop by skipping reading etc hosts file
  config/ubuntu2204.yaml
Labels: approved, size/XS, cncf-cla: yes

#327 Avoid coredns loop by skipping reading etc hosts file - Take 2
  kubetest2-ec2/config/ubuntu2204.yaml
Labels: cncf-cla: yes

#328 Avoid coredns loop by skipping reading etc hosts file - Take 3
  kubetest2-ec2/config/al2023.sh
Labels: approved, size/XS, cncf-cla: yes

#329 remove coredns loop plugin
  kubetest2-ec2/config/run-post-install.sh
Labels: approved, cncf-cla: yes

#330 Wait for coredns pods after we update the configmap
  kubetest2-ec2/config/run-post-install.sh
Labels: approved, size/XS, cncf-cla: yes

#331 Do the configmap surgery for coredns before doing other things
  kubetest2-ec2/config/run-post-install.sh
Labels: approved, size/S, cncf-cla: yes

#332 Do not remove loopback plugin from coredns
  kubetest2-ec2/config/run-post-install.sh
Labels: cncf-cla: yes

#334 Allow running off a fresh AL2023/AL2 image
  kubetest2-ec2/README.md
  kubetest2-ec2/config/al2023.sh
  kubetest2-ec2/config/embed.go
  kubetest2-ec2/config/run-post-install.sh
  kubetest2-ec2/pkg/deployer/dump.go
  kubetest2-ec2/pkg/deployer/runner.go
  kubetest2-ec2/pkg/deployer/utils/userdata.go
Labels: size/L, approved, cncf-cla: yes

#335 set resolv-conf explicitly
  kubetest2-ec2/config/al2023.sh
  kubetest2-ec2/config/kubeadm-init.yaml
  kubetest2-ec2/config/kubeadm-join.yaml
  kubetest2-ec2/config/run-post-install.sh
Labels: approved, size/S, cncf-cla: yes

#336 ignore if link destination already exists
  kubetest2-ec2/config/al2023.sh
Labels: approved, size/XS, cncf-cla: yes

#337 enable read permissions to grab container logs
  kubetest2-ec2/config/al2023.sh
Labels: approved, size/XS, cncf-cla: yes

#338 dump the entire journal logs
  kubetest2-ec2/pkg/deployer/dump.go
Labels: approved, cncf-cla: yes

#339 Duh fix the chmod params
  kubetest2-ec2/config/al2023.sh
Labels: approved, cncf-cla: yes

#340 set read permissions for pod logs
  kubetest2-ec2/pkg/deployer/dump.go
Labels: approved, size/XS, cncf-cla: yes

#341 remove extra pods/ directory
  kubetest2-ec2/pkg/deployer/dump.go
Labels: approved, cncf-cla: yes

#343 Still is not right, needs the instance id
  kubetest2-ec2/pkg/deployer/dump.go
Labels: approved, cncf-cla: yes

#346 Pick correct cidr from the VPC
  kubetest2-ec2/config/run-kubeadm.sh
Labels: approved, size/XS, cncf-cla: yes

#347 Update $HOME/.kube/config
  kubetest2-ec2/pkg/deployer/runner.go
  kubetest2-ec2/pkg/deployer/up.go
Labels: approved, size/XS, cncf-cla: yes

#349 Pick and specify a subnet/CIDR to start all the instances
  kubetest2-ec2/pkg/deployer/runner.go
  kubetest2-ec2/pkg/deployer/utils/ec2.go
Labels: approved, size/M, cncf-cla: yes

#351 enable write perms for kube config file
  kubetest2-ec2/pkg/deployer/up.go
Labels: approved, size/XS, cncf-cla: yes

#353 try both id_rsa and id_ed25519 one after another
  kubetest2-ec2/pkg/deployer/runner.go
  kubetest2-ec2/pkg/deployer/utils/sshkey.go
Labels: approved, size/S, cncf-cla: yes

#354 Skip us-east-1e for now
  kubetest2-ec2/pkg/deployer/utils/ec2.go
Labels: approved, size/XS, cncf-cla: yes

#358 Add more logging for kubetest2-ec2 assignNewSSHKey
  kubetest2-ec2/pkg/deployer/runner.go
Labels: approved, lgtm, size/XS, cncf-cla: yes
