Repository kubernetes-sigs/provider-aws-test-infra, pull requests merged in 2025-02, with the labels that each got.

#390 Remove the deprecated cloud provider flag for apiserver
  kubetest2-ec2/config/kubeadm-init.yaml
Labels: approved, lgtm, size/XS, cncf-cla: yes

#392 cd to k8sRoot before running script
  vendor/k8s.io/kubernetes/test/e2e_node/builder/build.go
Labels: approved, size/XS, cncf-cla: yes

#393 Bump Kubernetes on (02/27/2025)
  go.mod
  hack/make-rules/test-e2e-node.sh
  vendor/k8s.io/api/resource/v1alpha3/generated.pb.go
  vendor/k8s.io/api/resource/v1alpha3/generated.proto
  vendor/k8s.io/api/resource/v1alpha3/types.go
  vendor/k8s.io/api/resource/v1alpha3/types_swagger_doc_generated.go
  vendor/k8s.io/api/resource/v1alpha3/zz_generated.deepcopy.go
  vendor/k8s.io/api/resource/v1beta1/generated.pb.go
  vendor/k8s.io/api/resource/v1beta1/generated.proto
  vendor/k8s.io/api/resource/v1beta1/types.go
  vendor/k8s.io/api/resource/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/resource/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apimachinery/pkg/util/wait/wait.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/k8s.io/kubernetes/pkg/features/versioned_kube_features.go
  vendor/k8s.io/kubernetes/test/e2e_node/builder/build.go
  vendor/k8s.io/kubernetes/test/utils/image/manifest.go
  vendor/modules.txt
Labels: approved, size/XL, cncf-cla: yes
